// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: _Chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SCHATDATA_PIECE_ITEM_PROPERTY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pid string `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Pv  int32  `protobuf:"varint,2,opt,name=pv,proto3" json:"pv,omitempty"`
}

func (x *SCHATDATA_PIECE_ITEM_PROPERTY) Reset() {
	*x = SCHATDATA_PIECE_ITEM_PROPERTY{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCHATDATA_PIECE_ITEM_PROPERTY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHATDATA_PIECE_ITEM_PROPERTY) ProtoMessage() {}

func (x *SCHATDATA_PIECE_ITEM_PROPERTY) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHATDATA_PIECE_ITEM_PROPERTY.ProtoReflect.Descriptor instead.
func (*SCHATDATA_PIECE_ITEM_PROPERTY) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{0}
}

func (x *SCHATDATA_PIECE_ITEM_PROPERTY) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *SCHATDATA_PIECE_ITEM_PROPERTY) GetPv() int32 {
	if x != nil {
		return x.Pv
	}
	return 0
}

type SCHATDATA_PIECE_ITEM_ENCHANT_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pidx uint32 `protobuf:"varint,1,opt,name=pidx,proto3" json:"pidx,omitempty"`
	Miid string `protobuf:"bytes,2,opt,name=miid,proto3" json:"miid,omitempty"`
}

func (x *SCHATDATA_PIECE_ITEM_ENCHANT_INFO) Reset() {
	*x = SCHATDATA_PIECE_ITEM_ENCHANT_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCHATDATA_PIECE_ITEM_ENCHANT_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHATDATA_PIECE_ITEM_ENCHANT_INFO) ProtoMessage() {}

func (x *SCHATDATA_PIECE_ITEM_ENCHANT_INFO) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHATDATA_PIECE_ITEM_ENCHANT_INFO.ProtoReflect.Descriptor instead.
func (*SCHATDATA_PIECE_ITEM_ENCHANT_INFO) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{1}
}

func (x *SCHATDATA_PIECE_ITEM_ENCHANT_INFO) GetPidx() uint32 {
	if x != nil {
		return x.Pidx
	}
	return 0
}

func (x *SCHATDATA_PIECE_ITEM_ENCHANT_INFO) GetMiid() string {
	if x != nil {
		return x.Miid
	}
	return ""
}

type SCHATDATA_PIECE_ITEM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64                               `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Iid string                               `protobuf:"bytes,2,opt,name=iid,proto3" json:"iid,omitempty"`
	Pp  []*SCHATDATA_PIECE_ITEM_PROPERTY     `protobuf:"bytes,3,rep,name=pp,proto3" json:"pp,omitempty"`
	Sp  []*SCHATDATA_PIECE_ITEM_PROPERTY     `protobuf:"bytes,4,rep,name=sp,proto3" json:"sp,omitempty"`
	Se  []*SCHATDATA_PIECE_ITEM_ENCHANT_INFO `protobuf:"bytes,5,rep,name=se,proto3" json:"se,omitempty"`
}

func (x *SCHATDATA_PIECE_ITEM) Reset() {
	*x = SCHATDATA_PIECE_ITEM{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCHATDATA_PIECE_ITEM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHATDATA_PIECE_ITEM) ProtoMessage() {}

func (x *SCHATDATA_PIECE_ITEM) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHATDATA_PIECE_ITEM.ProtoReflect.Descriptor instead.
func (*SCHATDATA_PIECE_ITEM) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{2}
}

func (x *SCHATDATA_PIECE_ITEM) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SCHATDATA_PIECE_ITEM) GetIid() string {
	if x != nil {
		return x.Iid
	}
	return ""
}

func (x *SCHATDATA_PIECE_ITEM) GetPp() []*SCHATDATA_PIECE_ITEM_PROPERTY {
	if x != nil {
		return x.Pp
	}
	return nil
}

func (x *SCHATDATA_PIECE_ITEM) GetSp() []*SCHATDATA_PIECE_ITEM_PROPERTY {
	if x != nil {
		return x.Sp
	}
	return nil
}

func (x *SCHATDATA_PIECE_ITEM) GetSe() []*SCHATDATA_PIECE_ITEM_ENCHANT_INFO {
	if x != nil {
		return x.Se
	}
	return nil
}

type SCHATDATA_PIECE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatStr           string                `protobuf:"bytes,1,opt,name=chatStr,proto3" json:"chatStr,omitempty"`
	ChatDataPieceItem *SCHATDATA_PIECE_ITEM `protobuf:"bytes,2,opt,name=chatDataPieceItem,proto3" json:"chatDataPieceItem,omitempty"`
}

func (x *SCHATDATA_PIECE) Reset() {
	*x = SCHATDATA_PIECE{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCHATDATA_PIECE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHATDATA_PIECE) ProtoMessage() {}

func (x *SCHATDATA_PIECE) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHATDATA_PIECE.ProtoReflect.Descriptor instead.
func (*SCHATDATA_PIECE) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{3}
}

func (x *SCHATDATA_PIECE) GetChatStr() string {
	if x != nil {
		return x.ChatStr
	}
	return ""
}

func (x *SCHATDATA_PIECE) GetChatDataPieceItem() *SCHATDATA_PIECE_ITEM {
	if x != nil {
		return x.ChatDataPieceItem
	}
	return nil
}

type SCHATDATA struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId          string             `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	CharacterId        string             `protobuf:"bytes,2,opt,name=characterId,proto3" json:"characterId,omitempty"`
	Nickname           *SACCOUNT_NICKNAME `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	PartyId            string             `protobuf:"bytes,4,opt,name=partyId,proto3" json:"partyId,omitempty"`
	ChatDataPieceArray []*SCHATDATA_PIECE `protobuf:"bytes,5,rep,name=chatDataPieceArray,proto3" json:"chatDataPieceArray,omitempty"`
}

func (x *SCHATDATA) Reset() {
	*x = SCHATDATA{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCHATDATA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCHATDATA) ProtoMessage() {}

func (x *SCHATDATA) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCHATDATA.ProtoReflect.Descriptor instead.
func (*SCHATDATA) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{4}
}

func (x *SCHATDATA) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SCHATDATA) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *SCHATDATA) GetNickname() *SACCOUNT_NICKNAME {
	if x != nil {
		return x.Nickname
	}
	return nil
}

func (x *SCHATDATA) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *SCHATDATA) GetChatDataPieceArray() []*SCHATDATA_PIECE {
	if x != nil {
		return x.ChatDataPieceArray
	}
	return nil
}

type SPIECE_ITEM_BODY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idx    uint32                `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Pieces *SCHATDATA_PIECE_ITEM `protobuf:"bytes,2,opt,name=pieces,proto3" json:"pieces,omitempty"`
}

func (x *SPIECE_ITEM_BODY) Reset() {
	*x = SPIECE_ITEM_BODY{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPIECE_ITEM_BODY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPIECE_ITEM_BODY) ProtoMessage() {}

func (x *SPIECE_ITEM_BODY) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPIECE_ITEM_BODY.ProtoReflect.Descriptor instead.
func (*SPIECE_ITEM_BODY) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{5}
}

func (x *SPIECE_ITEM_BODY) GetIdx() uint32 {
	if x != nil {
		return x.Idx
	}
	return 0
}

func (x *SPIECE_ITEM_BODY) GetPieces() *SCHATDATA_PIECE_ITEM {
	if x != nil {
		return x.Pieces
	}
	return nil
}

type SPIECE_ITEM_ARRAY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Links []*SPIECE_ITEM_BODY `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
}

func (x *SPIECE_ITEM_ARRAY) Reset() {
	*x = SPIECE_ITEM_ARRAY{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Chat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPIECE_ITEM_ARRAY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPIECE_ITEM_ARRAY) ProtoMessage() {}

func (x *SPIECE_ITEM_ARRAY) ProtoReflect() protoreflect.Message {
	mi := &file___Chat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPIECE_ITEM_ARRAY.ProtoReflect.Descriptor instead.
func (*SPIECE_ITEM_ARRAY) Descriptor() ([]byte, []int) {
	return file___Chat_proto_rawDescGZIP(), []int{6}
}

func (x *SPIECE_ITEM_ARRAY) GetLinks() []*SPIECE_ITEM_BODY {
	if x != nil {
		return x.Links
	}
	return nil
}

var File___Chat_proto protoreflect.FileDescriptor

var file___Chat_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x5f, 0x43, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x44,
	0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x10, 0x5f, 0x43, 0x68, 0x61, 0x72, 0x61,
	0x63, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x1d, 0x53, 0x43,
	0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54,
	0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x12, 0x10, 0x0a, 0x03, 0x70,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x70, 0x76, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x70, 0x76, 0x22, 0x4b, 0x0a,
	0x21, 0x53, 0x43, 0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45,
	0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x45, 0x4e, 0x43, 0x48, 0x41, 0x4e, 0x54, 0x5f, 0x49, 0x4e,
	0x46, 0x4f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x64, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x70, 0x69, 0x64, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x69, 0x64, 0x22, 0xec, 0x01, 0x0a, 0x14, 0x53,
	0x43, 0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49,
	0x54, 0x45, 0x4d, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x69, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x02, 0x70, 0x70, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x53, 0x43, 0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f,
	0x49, 0x54, 0x45, 0x4d, 0x5f, 0x50, 0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x52, 0x02, 0x70,
	0x70, 0x12, 0x38, 0x0a, 0x02, 0x73, 0x70, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x48, 0x41, 0x54, 0x44,
	0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x50,
	0x52, 0x4f, 0x50, 0x45, 0x52, 0x54, 0x59, 0x52, 0x02, 0x73, 0x70, 0x12, 0x3c, 0x0a, 0x02, 0x73,
	0x65, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49,
	0x45, 0x43, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x45, 0x4e, 0x43, 0x48, 0x41, 0x4e, 0x54,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x02, 0x73, 0x65, 0x22, 0x7a, 0x0a, 0x0f, 0x53, 0x43, 0x48,
	0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x61, 0x74, 0x53, 0x74, 0x72, 0x12, 0x4d, 0x0a, 0x11, 0x63, 0x68, 0x61, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x69, 0x65, 0x63, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1f, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x43,
	0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54,
	0x45, 0x4d, 0x52, 0x11, 0x63, 0x68, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x69, 0x65, 0x63,
	0x65, 0x49, 0x74, 0x65, 0x6d, 0x22, 0xeb, 0x01, 0x0a, 0x09, 0x53, 0x43, 0x48, 0x41, 0x54, 0x44,
	0x41, 0x54, 0x41, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x38, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x53, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x4e, 0x49, 0x43, 0x4b, 0x4e,
	0x41, 0x4d, 0x45, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x12, 0x4a, 0x0a, 0x12, 0x63, 0x68, 0x61, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x69, 0x65, 0x63, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x53, 0x43, 0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x50, 0x49, 0x45, 0x43, 0x45, 0x52,
	0x12, 0x63, 0x68, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x69, 0x65, 0x63, 0x65, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x22, 0x5d, 0x0a, 0x10, 0x53, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54,
	0x45, 0x4d, 0x5f, 0x42, 0x4f, 0x44, 0x59, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x69, 0x64, 0x78, 0x12, 0x37, 0x0a, 0x06, 0x70, 0x69, 0x65,
	0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x44, 0x43, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x43, 0x48, 0x41, 0x54, 0x44, 0x41, 0x54, 0x41, 0x5f,
	0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x52, 0x06, 0x70, 0x69, 0x65, 0x63,
	0x65, 0x73, 0x22, 0x46, 0x0a, 0x11, 0x53, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54, 0x45,
	0x4d, 0x5f, 0x41, 0x52, 0x52, 0x41, 0x59, 0x12, 0x31, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x53, 0x50, 0x49, 0x45, 0x43, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x42,
	0x4f, 0x44, 0x59, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x42, 0x31, 0x0a, 0x10, 0x63, 0x6f,
	0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x42, 0x04,
	0x63, 0x68, 0x61, 0x74, 0x50, 0x00, 0x5a, 0x15, 0x64, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file___Chat_proto_rawDescOnce sync.Once
	file___Chat_proto_rawDescData = file___Chat_proto_rawDesc
)

func file___Chat_proto_rawDescGZIP() []byte {
	file___Chat_proto_rawDescOnce.Do(func() {
		file___Chat_proto_rawDescData = protoimpl.X.CompressGZIP(file___Chat_proto_rawDescData)
	})
	return file___Chat_proto_rawDescData
}

var file___Chat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file___Chat_proto_goTypes = []interface{}{
	(*SCHATDATA_PIECE_ITEM_PROPERTY)(nil),     // 0: DC.Packet.SCHATDATA_PIECE_ITEM_PROPERTY
	(*SCHATDATA_PIECE_ITEM_ENCHANT_INFO)(nil), // 1: DC.Packet.SCHATDATA_PIECE_ITEM_ENCHANT_INFO
	(*SCHATDATA_PIECE_ITEM)(nil),              // 2: DC.Packet.SCHATDATA_PIECE_ITEM
	(*SCHATDATA_PIECE)(nil),                   // 3: DC.Packet.SCHATDATA_PIECE
	(*SCHATDATA)(nil),                         // 4: DC.Packet.SCHATDATA
	(*SPIECE_ITEM_BODY)(nil),                  // 5: DC.Packet.SPIECE_ITEM_BODY
	(*SPIECE_ITEM_ARRAY)(nil),                 // 6: DC.Packet.SPIECE_ITEM_ARRAY
	(*SACCOUNT_NICKNAME)(nil),                 // 7: DC.Packet.SACCOUNT_NICKNAME
}
var file___Chat_proto_depIdxs = []int32{
	0, // 0: DC.Packet.SCHATDATA_PIECE_ITEM.pp:type_name -> DC.Packet.SCHATDATA_PIECE_ITEM_PROPERTY
	0, // 1: DC.Packet.SCHATDATA_PIECE_ITEM.sp:type_name -> DC.Packet.SCHATDATA_PIECE_ITEM_PROPERTY
	1, // 2: DC.Packet.SCHATDATA_PIECE_ITEM.se:type_name -> DC.Packet.SCHATDATA_PIECE_ITEM_ENCHANT_INFO
	2, // 3: DC.Packet.SCHATDATA_PIECE.chatDataPieceItem:type_name -> DC.Packet.SCHATDATA_PIECE_ITEM
	7, // 4: DC.Packet.SCHATDATA.nickname:type_name -> DC.Packet.SACCOUNT_NICKNAME
	3, // 5: DC.Packet.SCHATDATA.chatDataPieceArray:type_name -> DC.Packet.SCHATDATA_PIECE
	2, // 6: DC.Packet.SPIECE_ITEM_BODY.pieces:type_name -> DC.Packet.SCHATDATA_PIECE_ITEM
	5, // 7: DC.Packet.SPIECE_ITEM_ARRAY.links:type_name -> DC.Packet.SPIECE_ITEM_BODY
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file___Chat_proto_init() }
func file___Chat_proto_init() {
	if File___Chat_proto != nil {
		return
	}
	file___Character_proto_init()
	if !protoimpl.UnsafeEnabled {
		file___Chat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCHATDATA_PIECE_ITEM_PROPERTY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Chat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCHATDATA_PIECE_ITEM_ENCHANT_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Chat_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCHATDATA_PIECE_ITEM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Chat_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCHATDATA_PIECE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Chat_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCHATDATA); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Chat_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPIECE_ITEM_BODY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Chat_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPIECE_ITEM_ARRAY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file___Chat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___Chat_proto_goTypes,
		DependencyIndexes: file___Chat_proto_depIdxs,
		MessageInfos:      file___Chat_proto_msgTypes,
	}.Build()
	File___Chat_proto = out.File
	file___Chat_proto_rawDesc = nil
	file___Chat_proto_goTypes = nil
	file___Chat_proto_depIdxs = nil
}
