// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: Inventory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO int32

const (
	SS2C_INVENTORY_INFO_RES_NONE          SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO = 0
	SS2C_INVENTORY_INFO_RES_OK_SEND_DATA  SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO = 1
	SS2C_INVENTORY_INFO_RES_OK_NOT_CHANGE SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO = 2
	SS2C_INVENTORY_INFO_RES_FAIL          SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO = 3
)

// Enum value maps for SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO.
var (
	SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO_name = map[int32]string{
		0: "NONE",
		1: "OK_SEND_DATA",
		2: "OK_NOT_CHANGE",
		3: "FAIL",
	}
	SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO_value = map[string]int32{
		"NONE":          0,
		"OK_SEND_DATA":  1,
		"OK_NOT_CHANGE": 2,
		"FAIL":          3,
	}
)

func (x SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO) Enum() *SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO {
	p := new(SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO)
	*p = x
	return p
}

func (x SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO) Descriptor() protoreflect.EnumDescriptor {
	return file_Inventory_proto_enumTypes[0].Descriptor()
}

func (SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO) Type() protoreflect.EnumType {
	return &file_Inventory_proto_enumTypes[0]
}

func (x SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO.Descriptor instead.
func (SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO) EnumDescriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{3, 0}
}

type SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE int32

const (
	SS2C_INVENTORY_ALL_UPDATE_RES_NONE SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE = 0
	SS2C_INVENTORY_ALL_UPDATE_RES_OK   SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE = 1
	SS2C_INVENTORY_ALL_UPDATE_RES_FAIL SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE = 2
)

// Enum value maps for SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE.
var (
	SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE_name = map[int32]string{
		0: "NONE",
		1: "OK",
		2: "FAIL",
	}
	SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE_value = map[string]int32{
		"NONE": 0,
		"OK":   1,
		"FAIL": 2,
	}
)

func (x SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE) Enum() *SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE {
	p := new(SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE)
	*p = x
	return p
}

func (x SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE) Descriptor() protoreflect.EnumDescriptor {
	return file_Inventory_proto_enumTypes[1].Descriptor()
}

func (SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE) Type() protoreflect.EnumType {
	return &file_Inventory_proto_enumTypes[1]
}

func (x SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE.Descriptor instead.
func (SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE) EnumDescriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{5, 0}
}

type SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE int32

const (
	SS2C_INVENTORY_SINGLE_UPDATE_RES_NONE                      SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE = 0
	SS2C_INVENTORY_SINGLE_UPDATE_RES_OK                        SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE = 1
	SS2C_INVENTORY_SINGLE_UPDATE_RES_FAIL                      SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE = 2
	SS2C_INVENTORY_SINGLE_UPDATE_RES_FAIL_VALID_CHECK_OLD_ITEM SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE = 3
	SS2C_INVENTORY_SINGLE_UPDATE_RES_FAIL_VALID_CHECK_NEW_ITEM SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE = 4
	SS2C_INVENTORY_SINGLE_UPDATE_RES_FAIL_CHECK_LOGIC_LOG      SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE = 5
)

// Enum value maps for SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE.
var (
	SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE_name = map[int32]string{
		0: "NONE",
		1: "OK",
		2: "FAIL",
		3: "FAIL_VALID_CHECK_OLD_ITEM",
		4: "FAIL_VALID_CHECK_NEW_ITEM",
		5: "FAIL_CHECK_LOGIC_LOG",
	}
	SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE_value = map[string]int32{
		"NONE":                      0,
		"OK":                        1,
		"FAIL":                      2,
		"FAIL_VALID_CHECK_OLD_ITEM": 3,
		"FAIL_VALID_CHECK_NEW_ITEM": 4,
		"FAIL_CHECK_LOGIC_LOG":      5,
	}
)

func (x SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE) Enum() *SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE {
	p := new(SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE)
	*p = x
	return p
}

func (x SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE) Descriptor() protoreflect.EnumDescriptor {
	return file_Inventory_proto_enumTypes[2].Descriptor()
}

func (SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE) Type() protoreflect.EnumType {
	return &file_Inventory_proto_enumTypes[2]
}

func (x SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE.Descriptor instead.
func (SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE) EnumDescriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{23, 0}
}

type SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO int32

const (
	SS2C_STORAGE_INFO_RES_NONE          SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO = 0
	SS2C_STORAGE_INFO_RES_OK_SEND_DATA  SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO = 1
	SS2C_STORAGE_INFO_RES_OK_NOT_CHANGE SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO = 2
	SS2C_STORAGE_INFO_RES_FAIL          SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO = 3
)

// Enum value maps for SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO.
var (
	SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO_name = map[int32]string{
		0: "NONE",
		1: "OK_SEND_DATA",
		2: "OK_NOT_CHANGE",
		3: "FAIL",
	}
	SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO_value = map[string]int32{
		"NONE":          0,
		"OK_SEND_DATA":  1,
		"OK_NOT_CHANGE": 2,
		"FAIL":          3,
	}
)

func (x SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO) Enum() *SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO {
	p := new(SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO)
	*p = x
	return p
}

func (x SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO) Descriptor() protoreflect.EnumDescriptor {
	return file_Inventory_proto_enumTypes[3].Descriptor()
}

func (SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO) Type() protoreflect.EnumType {
	return &file_Inventory_proto_enumTypes[3]
}

func (x SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO.Descriptor instead.
func (SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO) EnumDescriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{25, 0}
}

type SINVENTORY_REQUEST_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemUniqueId      uint64 `protobuf:"varint,1,opt,name=itemUniqueId,proto3" json:"itemUniqueId,omitempty"`
	ItemCount         uint32 `protobuf:"varint,2,opt,name=itemCount,proto3" json:"itemCount,omitempty"`
	ItemContentsCount uint32 `protobuf:"varint,3,opt,name=itemContentsCount,proto3" json:"itemContentsCount,omitempty"`
}

func (x *SINVENTORY_REQUEST_INFO) Reset() {
	*x = SINVENTORY_REQUEST_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SINVENTORY_REQUEST_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SINVENTORY_REQUEST_INFO) ProtoMessage() {}

func (x *SINVENTORY_REQUEST_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SINVENTORY_REQUEST_INFO.ProtoReflect.Descriptor instead.
func (*SINVENTORY_REQUEST_INFO) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{0}
}

func (x *SINVENTORY_REQUEST_INFO) GetItemUniqueId() uint64 {
	if x != nil {
		return x.ItemUniqueId
	}
	return 0
}

func (x *SINVENTORY_REQUEST_INFO) GetItemCount() uint32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *SINVENTORY_REQUEST_INFO) GetItemContentsCount() uint32 {
	if x != nil {
		return x.ItemContentsCount
	}
	return 0
}

type SINVENTORY_RESULT_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InsertItems     []*SItem `protobuf:"bytes,1,rep,name=insertItems,proto3" json:"insertItems,omitempty"`
	UpdateItems     []*SItem `protobuf:"bytes,2,rep,name=updateItems,proto3" json:"updateItems,omitempty"`
	DeleteUniqueIds []int64  `protobuf:"varint,3,rep,packed,name=deleteUniqueIds,proto3" json:"deleteUniqueIds,omitempty"`
}

func (x *SINVENTORY_RESULT_INFO) Reset() {
	*x = SINVENTORY_RESULT_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SINVENTORY_RESULT_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SINVENTORY_RESULT_INFO) ProtoMessage() {}

func (x *SINVENTORY_RESULT_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SINVENTORY_RESULT_INFO.ProtoReflect.Descriptor instead.
func (*SINVENTORY_RESULT_INFO) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{1}
}

func (x *SINVENTORY_RESULT_INFO) GetInsertItems() []*SItem {
	if x != nil {
		return x.InsertItems
	}
	return nil
}

func (x *SINVENTORY_RESULT_INFO) GetUpdateItems() []*SItem {
	if x != nil {
		return x.UpdateItems
	}
	return nil
}

func (x *SINVENTORY_RESULT_INFO) GetDeleteUniqueIds() []int64 {
	if x != nil {
		return x.DeleteUniqueIds
	}
	return nil
}

type SC2S_INVENTORY_INFO_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SC2S_INVENTORY_INFO_REQ) Reset() {
	*x = SC2S_INVENTORY_INFO_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_INFO_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_INFO_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_INFO_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_INFO_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_INFO_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{2}
}

type SS2C_INVENTORY_INFO_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result         uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	InventoryItems []*SItem `protobuf:"bytes,2,rep,name=inventoryItems,proto3" json:"inventoryItems,omitempty"`
}

func (x *SS2C_INVENTORY_INFO_RES) Reset() {
	*x = SS2C_INVENTORY_INFO_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_INFO_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_INFO_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_INFO_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_INFO_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_INFO_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{3}
}

func (x *SS2C_INVENTORY_INFO_RES) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SS2C_INVENTORY_INFO_RES) GetInventoryItems() []*SItem {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

type SC2S_INVENTORY_ALL_UPDATE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InventoryItems []*SItem `protobuf:"bytes,1,rep,name=inventoryItems,proto3" json:"inventoryItems,omitempty"`
}

func (x *SC2S_INVENTORY_ALL_UPDATE_REQ) Reset() {
	*x = SC2S_INVENTORY_ALL_UPDATE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_ALL_UPDATE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_ALL_UPDATE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_ALL_UPDATE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_ALL_UPDATE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_ALL_UPDATE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{4}
}

func (x *SC2S_INVENTORY_ALL_UPDATE_REQ) GetInventoryItems() []*SItem {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

type SS2C_INVENTORY_ALL_UPDATE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result         uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	InventoryItems []*SItem `protobuf:"bytes,2,rep,name=inventoryItems,proto3" json:"inventoryItems,omitempty"`
}

func (x *SS2C_INVENTORY_ALL_UPDATE_RES) Reset() {
	*x = SS2C_INVENTORY_ALL_UPDATE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_ALL_UPDATE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_ALL_UPDATE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_ALL_UPDATE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_ALL_UPDATE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_ALL_UPDATE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{5}
}

func (x *SS2C_INVENTORY_ALL_UPDATE_RES) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SS2C_INVENTORY_ALL_UPDATE_RES) GetInventoryItems() []*SItem {
	if x != nil {
		return x.InventoryItems
	}
	return nil
}

type SINVENTORY_ITEM_REQ_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UniqueId    uint64 `protobuf:"varint,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	InventoryId uint32 `protobuf:"varint,2,opt,name=inventoryId,proto3" json:"inventoryId,omitempty"`
	SlotId      uint32 `protobuf:"varint,3,opt,name=slotId,proto3" json:"slotId,omitempty"`
}

func (x *SINVENTORY_ITEM_REQ_INFO) Reset() {
	*x = SINVENTORY_ITEM_REQ_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SINVENTORY_ITEM_REQ_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SINVENTORY_ITEM_REQ_INFO) ProtoMessage() {}

func (x *SINVENTORY_ITEM_REQ_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SINVENTORY_ITEM_REQ_INFO.ProtoReflect.Descriptor instead.
func (*SINVENTORY_ITEM_REQ_INFO) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{6}
}

func (x *SINVENTORY_ITEM_REQ_INFO) GetUniqueId() uint64 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *SINVENTORY_ITEM_REQ_INFO) GetInventoryId() uint32 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *SINVENTORY_ITEM_REQ_INFO) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

type SC2S_INVENTORY_MOVE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	DstInventoryId uint32                    `protobuf:"varint,2,opt,name=dstInventoryId,proto3" json:"dstInventoryId,omitempty"`
	DstSlotId      uint32                    `protobuf:"varint,3,opt,name=dstSlotId,proto3" json:"dstSlotId,omitempty"`
}

func (x *SC2S_INVENTORY_MOVE_REQ) Reset() {
	*x = SC2S_INVENTORY_MOVE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_MOVE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_MOVE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_MOVE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_MOVE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_MOVE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{7}
}

func (x *SC2S_INVENTORY_MOVE_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_MOVE_REQ) GetDstInventoryId() uint32 {
	if x != nil {
		return x.DstInventoryId
	}
	return 0
}

func (x *SC2S_INVENTORY_MOVE_REQ) GetDstSlotId() uint32 {
	if x != nil {
		return x.DstSlotId
	}
	return 0
}

type SS2C_INVENTORY_MOVE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS2C_INVENTORY_MOVE_RES) Reset() {
	*x = SS2C_INVENTORY_MOVE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_MOVE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_MOVE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_MOVE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_MOVE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_MOVE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{8}
}

type SC2S_INVENTORY_MERGE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	DstInfo *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,2,opt,name=dstInfo,proto3" json:"dstInfo,omitempty"`
}

func (x *SC2S_INVENTORY_MERGE_REQ) Reset() {
	*x = SC2S_INVENTORY_MERGE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_MERGE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_MERGE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_MERGE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_MERGE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_MERGE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{9}
}

func (x *SC2S_INVENTORY_MERGE_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_MERGE_REQ) GetDstInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.DstInfo
	}
	return nil
}

type SS2C_INVENTORY_MERGE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS2C_INVENTORY_MERGE_RES) Reset() {
	*x = SS2C_INVENTORY_MERGE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_MERGE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_MERGE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_MERGE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_MERGE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_MERGE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{10}
}

type INVENTORY_SWAP_DST_INFO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DstInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=dstInfo,proto3" json:"dstInfo,omitempty"`
	NewSlotId      uint32                    `protobuf:"varint,2,opt,name=newSlotId,proto3" json:"newSlotId,omitempty"`
	NewInventoryId uint32                    `protobuf:"varint,3,opt,name=newInventoryId,proto3" json:"newInventoryId,omitempty"`
}

func (x *INVENTORY_SWAP_DST_INFO) Reset() {
	*x = INVENTORY_SWAP_DST_INFO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *INVENTORY_SWAP_DST_INFO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*INVENTORY_SWAP_DST_INFO) ProtoMessage() {}

func (x *INVENTORY_SWAP_DST_INFO) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use INVENTORY_SWAP_DST_INFO.ProtoReflect.Descriptor instead.
func (*INVENTORY_SWAP_DST_INFO) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{11}
}

func (x *INVENTORY_SWAP_DST_INFO) GetDstInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.DstInfo
	}
	return nil
}

func (x *INVENTORY_SWAP_DST_INFO) GetNewSlotId() uint32 {
	if x != nil {
		return x.NewSlotId
	}
	return 0
}

func (x *INVENTORY_SWAP_DST_INFO) GetNewInventoryId() uint32 {
	if x != nil {
		return x.NewInventoryId
	}
	return 0
}

type SC2S_INVENTORY_SWAP_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo   *SINVENTORY_ITEM_REQ_INFO  `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	DstInfo   *SINVENTORY_ITEM_REQ_INFO  `protobuf:"bytes,2,opt,name=dstInfo,proto3" json:"dstInfo,omitempty"`
	SwapInfos []*INVENTORY_SWAP_DST_INFO `protobuf:"bytes,3,rep,name=swapInfos,proto3" json:"swapInfos,omitempty"`
}

func (x *SC2S_INVENTORY_SWAP_REQ) Reset() {
	*x = SC2S_INVENTORY_SWAP_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_SWAP_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_SWAP_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_SWAP_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_SWAP_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_SWAP_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{12}
}

func (x *SC2S_INVENTORY_SWAP_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SWAP_REQ) GetDstInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.DstInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SWAP_REQ) GetSwapInfos() []*INVENTORY_SWAP_DST_INFO {
	if x != nil {
		return x.SwapInfos
	}
	return nil
}

type SS2C_INVENTORY_SWAP_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS2C_INVENTORY_SWAP_RES) Reset() {
	*x = SS2C_INVENTORY_SWAP_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_SWAP_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_SWAP_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_SWAP_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_SWAP_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_SWAP_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{13}
}

type SC2S_INVENTORY_SPLIT_MOVE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	Count          uint32                    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	DstInventoryId uint32                    `protobuf:"varint,3,opt,name=dstInventoryId,proto3" json:"dstInventoryId,omitempty"`
	DstSlotId      uint32                    `protobuf:"varint,4,opt,name=dstSlotId,proto3" json:"dstSlotId,omitempty"`
}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) Reset() {
	*x = SC2S_INVENTORY_SPLIT_MOVE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_SPLIT_MOVE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_SPLIT_MOVE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_SPLIT_MOVE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{14}
}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) GetDstInventoryId() uint32 {
	if x != nil {
		return x.DstInventoryId
	}
	return 0
}

func (x *SC2S_INVENTORY_SPLIT_MOVE_REQ) GetDstSlotId() uint32 {
	if x != nil {
		return x.DstSlotId
	}
	return 0
}

type SS2C_INVENTORY_SPLIT_MOVE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewUniqueId    uint64 `protobuf:"varint,1,opt,name=newUniqueId,proto3" json:"newUniqueId,omitempty"`
	NewInventoryId uint32 `protobuf:"varint,2,opt,name=newInventoryId,proto3" json:"newInventoryId,omitempty"`
	NewSlotId      uint32 `protobuf:"varint,3,opt,name=newSlotId,proto3" json:"newSlotId,omitempty"`
}

func (x *SS2C_INVENTORY_SPLIT_MOVE_RES) Reset() {
	*x = SS2C_INVENTORY_SPLIT_MOVE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_SPLIT_MOVE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_SPLIT_MOVE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_SPLIT_MOVE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_SPLIT_MOVE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_SPLIT_MOVE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{15}
}

func (x *SS2C_INVENTORY_SPLIT_MOVE_RES) GetNewUniqueId() uint64 {
	if x != nil {
		return x.NewUniqueId
	}
	return 0
}

func (x *SS2C_INVENTORY_SPLIT_MOVE_RES) GetNewInventoryId() uint32 {
	if x != nil {
		return x.NewInventoryId
	}
	return 0
}

func (x *SS2C_INVENTORY_SPLIT_MOVE_RES) GetNewSlotId() uint32 {
	if x != nil {
		return x.NewSlotId
	}
	return 0
}

type SC2S_INVENTORY_SPLIT_MERGE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	DstInfo *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,2,opt,name=dstInfo,proto3" json:"dstInfo,omitempty"`
	Count   uint32                    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *SC2S_INVENTORY_SPLIT_MERGE_REQ) Reset() {
	*x = SC2S_INVENTORY_SPLIT_MERGE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_SPLIT_MERGE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_SPLIT_MERGE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_SPLIT_MERGE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_SPLIT_MERGE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_SPLIT_MERGE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{16}
}

func (x *SC2S_INVENTORY_SPLIT_MERGE_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SPLIT_MERGE_REQ) GetDstInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.DstInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SPLIT_MERGE_REQ) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SS2C_INVENTORY_SPLIT_MERGE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS2C_INVENTORY_SPLIT_MERGE_RES) Reset() {
	*x = SS2C_INVENTORY_SPLIT_MERGE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_SPLIT_MERGE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_SPLIT_MERGE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_SPLIT_MERGE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_SPLIT_MERGE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_SPLIT_MERGE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{17}
}

type SC2S_INVENTORY_SPLIT_SWAP_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	DstInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,2,opt,name=dstInfo,proto3" json:"dstInfo,omitempty"`
	Count          uint32                    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	NewSlotId      uint32                    `protobuf:"varint,4,opt,name=newSlotId,proto3" json:"newSlotId,omitempty"`
	NewInventoryId uint32                    `protobuf:"varint,5,opt,name=newInventoryId,proto3" json:"newInventoryId,omitempty"`
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) Reset() {
	*x = SC2S_INVENTORY_SPLIT_SWAP_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_SPLIT_SWAP_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_SPLIT_SWAP_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_SPLIT_SWAP_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{18}
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) GetDstInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.DstInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) GetNewSlotId() uint32 {
	if x != nil {
		return x.NewSlotId
	}
	return 0
}

func (x *SC2S_INVENTORY_SPLIT_SWAP_REQ) GetNewInventoryId() uint32 {
	if x != nil {
		return x.NewInventoryId
	}
	return 0
}

type SS2C_INVENTORY_SPLIT_SWAP_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewUniqueId    uint64 `protobuf:"varint,1,opt,name=newUniqueId,proto3" json:"newUniqueId,omitempty"`
	NewInventoryId uint32 `protobuf:"varint,2,opt,name=newInventoryId,proto3" json:"newInventoryId,omitempty"`
	NewSlotId      uint32 `protobuf:"varint,3,opt,name=newSlotId,proto3" json:"newSlotId,omitempty"`
}

func (x *SS2C_INVENTORY_SPLIT_SWAP_RES) Reset() {
	*x = SS2C_INVENTORY_SPLIT_SWAP_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_SPLIT_SWAP_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_SPLIT_SWAP_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_SPLIT_SWAP_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_SPLIT_SWAP_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_SPLIT_SWAP_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{19}
}

func (x *SS2C_INVENTORY_SPLIT_SWAP_RES) GetNewUniqueId() uint64 {
	if x != nil {
		return x.NewUniqueId
	}
	return 0
}

func (x *SS2C_INVENTORY_SPLIT_SWAP_RES) GetNewInventoryId() uint32 {
	if x != nil {
		return x.NewInventoryId
	}
	return 0
}

func (x *SS2C_INVENTORY_SPLIT_SWAP_RES) GetNewSlotId() uint32 {
	if x != nil {
		return x.NewSlotId
	}
	return 0
}

type SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,1,opt,name=srcInfo,proto3" json:"srcInfo,omitempty"`
	DstInfo        *SINVENTORY_ITEM_REQ_INFO `protobuf:"bytes,2,opt,name=dstInfo,proto3" json:"dstInfo,omitempty"`
	NewSlotId      uint32                    `protobuf:"varint,3,opt,name=newSlotId,proto3" json:"newSlotId,omitempty"`
	NewInventoryId uint32                    `protobuf:"varint,4,opt,name=newInventoryId,proto3" json:"newInventoryId,omitempty"`
}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) Reset() {
	*x = SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{20}
}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) GetSrcInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.SrcInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) GetDstInfo() *SINVENTORY_ITEM_REQ_INFO {
	if x != nil {
		return x.DstInfo
	}
	return nil
}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) GetNewSlotId() uint32 {
	if x != nil {
		return x.NewSlotId
	}
	return 0
}

func (x *SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ) GetNewInventoryId() uint32 {
	if x != nil {
		return x.NewInventoryId
	}
	return 0
}

type SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES) Reset() {
	*x = SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{21}
}

type SC2S_INVENTORY_SINGLE_UPDATE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SingleUpdateFlag uint32   `protobuf:"varint,1,opt,name=singleUpdateFlag,proto3" json:"singleUpdateFlag,omitempty"`
	OldItem          []*SItem `protobuf:"bytes,2,rep,name=oldItem,proto3" json:"oldItem,omitempty"`
	NewItem          []*SItem `protobuf:"bytes,3,rep,name=newItem,proto3" json:"newItem,omitempty"`
}

func (x *SC2S_INVENTORY_SINGLE_UPDATE_REQ) Reset() {
	*x = SC2S_INVENTORY_SINGLE_UPDATE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_SINGLE_UPDATE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_SINGLE_UPDATE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_SINGLE_UPDATE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_SINGLE_UPDATE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_SINGLE_UPDATE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{22}
}

func (x *SC2S_INVENTORY_SINGLE_UPDATE_REQ) GetSingleUpdateFlag() uint32 {
	if x != nil {
		return x.SingleUpdateFlag
	}
	return 0
}

func (x *SC2S_INVENTORY_SINGLE_UPDATE_REQ) GetOldItem() []*SItem {
	if x != nil {
		return x.OldItem
	}
	return nil
}

func (x *SC2S_INVENTORY_SINGLE_UPDATE_REQ) GetNewItem() []*SItem {
	if x != nil {
		return x.NewItem
	}
	return nil
}

type SS2C_INVENTORY_SINGLE_UPDATE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	OldItem []*SItem `protobuf:"bytes,2,rep,name=oldItem,proto3" json:"oldItem,omitempty"`
	NewItem []*SItem `protobuf:"bytes,3,rep,name=newItem,proto3" json:"newItem,omitempty"`
}

func (x *SS2C_INVENTORY_SINGLE_UPDATE_RES) Reset() {
	*x = SS2C_INVENTORY_SINGLE_UPDATE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_SINGLE_UPDATE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_SINGLE_UPDATE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_SINGLE_UPDATE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_SINGLE_UPDATE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_SINGLE_UPDATE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{23}
}

func (x *SS2C_INVENTORY_SINGLE_UPDATE_RES) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SS2C_INVENTORY_SINGLE_UPDATE_RES) GetOldItem() []*SItem {
	if x != nil {
		return x.OldItem
	}
	return nil
}

func (x *SS2C_INVENTORY_SINGLE_UPDATE_RES) GetNewItem() []*SItem {
	if x != nil {
		return x.NewItem
	}
	return nil
}

type SC2S_STORAGE_INFO_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRefresh uint32 `protobuf:"varint,1,opt,name=isRefresh,proto3" json:"isRefresh,omitempty"`
}

func (x *SC2S_STORAGE_INFO_REQ) Reset() {
	*x = SC2S_STORAGE_INFO_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_STORAGE_INFO_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_STORAGE_INFO_REQ) ProtoMessage() {}

func (x *SC2S_STORAGE_INFO_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_STORAGE_INFO_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_STORAGE_INFO_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{24}
}

func (x *SC2S_STORAGE_INFO_REQ) GetIsRefresh() uint32 {
	if x != nil {
		return x.IsRefresh
	}
	return 0
}

type SS2C_STORAGE_INFO_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result       uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	StorageItems []*SItem `protobuf:"bytes,2,rep,name=storageItems,proto3" json:"storageItems,omitempty"`
}

func (x *SS2C_STORAGE_INFO_RES) Reset() {
	*x = SS2C_STORAGE_INFO_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_STORAGE_INFO_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_STORAGE_INFO_RES) ProtoMessage() {}

func (x *SS2C_STORAGE_INFO_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_STORAGE_INFO_RES.ProtoReflect.Descriptor instead.
func (*SS2C_STORAGE_INFO_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{25}
}

func (x *SS2C_STORAGE_INFO_RES) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *SS2C_STORAGE_INFO_RES) GetStorageItems() []*SItem {
	if x != nil {
		return x.StorageItems
	}
	return nil
}

type SC2S_INVENTORY_EXPAND_STORAGE_REQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BuyInventoryId int32 `protobuf:"varint,1,opt,name=buyInventoryId,proto3" json:"buyInventoryId,omitempty"`
}

func (x *SC2S_INVENTORY_EXPAND_STORAGE_REQ) Reset() {
	*x = SC2S_INVENTORY_EXPAND_STORAGE_REQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SC2S_INVENTORY_EXPAND_STORAGE_REQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SC2S_INVENTORY_EXPAND_STORAGE_REQ) ProtoMessage() {}

func (x *SC2S_INVENTORY_EXPAND_STORAGE_REQ) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SC2S_INVENTORY_EXPAND_STORAGE_REQ.ProtoReflect.Descriptor instead.
func (*SC2S_INVENTORY_EXPAND_STORAGE_REQ) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{26}
}

func (x *SC2S_INVENTORY_EXPAND_STORAGE_REQ) GetBuyInventoryId() int32 {
	if x != nil {
		return x.BuyInventoryId
	}
	return 0
}

type SS2C_INVENTORY_EXPAND_STORAGE_RES struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result uint32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SS2C_INVENTORY_EXPAND_STORAGE_RES) Reset() {
	*x = SS2C_INVENTORY_EXPAND_STORAGE_RES{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Inventory_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SS2C_INVENTORY_EXPAND_STORAGE_RES) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SS2C_INVENTORY_EXPAND_STORAGE_RES) ProtoMessage() {}

func (x *SS2C_INVENTORY_EXPAND_STORAGE_RES) ProtoReflect() protoreflect.Message {
	mi := &file_Inventory_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SS2C_INVENTORY_EXPAND_STORAGE_RES.ProtoReflect.Descriptor instead.
func (*SS2C_INVENTORY_EXPAND_STORAGE_RES) Descriptor() ([]byte, []int) {
	return file_Inventory_proto_rawDescGZIP(), []int{27}
}

func (x *SS2C_INVENTORY_EXPAND_STORAGE_RES) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_Inventory_proto protoreflect.FileDescriptor

var file_Inventory_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x0b, 0x5f, 0x49,
	0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x17, 0x53, 0x49,
	0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x69, 0x74, 0x65,
	0x6d, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65,
	0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x69, 0x74, 0x65, 0x6d, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x11, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xaa, 0x01, 0x0a, 0x16, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e,
	0x54, 0x4f, 0x52, 0x59, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x49, 0x4e, 0x46, 0x4f,
	0x12, 0x32, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x12, 0x32, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0b, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49,
	0x64, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e,
	0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x22, 0xc2, 0x01,
	0x0a, 0x17, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x38, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0e, 0x69, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x55, 0x0a, 0x1a, 0x52,
	0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x4f, 0x4b, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x44,
	0x41, 0x54, 0x41, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x4b, 0x5f, 0x4e, 0x4f, 0x54, 0x5f,
	0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c,
	0x10, 0x03, 0x22, 0x59, 0x0a, 0x1d, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e,
	0x54, 0x4f, 0x52, 0x59, 0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f,
	0x52, 0x45, 0x51, 0x12, 0x38, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x0e, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xa8, 0x01,
	0x0a, 0x1d, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59,
	0x5f, 0x41, 0x4c, 0x4c, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d,
	0x73, 0x22, 0x35, 0x0a, 0x17, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x45,
	0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x22, 0x70, 0x0a, 0x18, 0x53, 0x49, 0x4e, 0x56,
	0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x17, 0x53,
	0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x4d, 0x4f,
	0x56, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49,
	0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x73, 0x72,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x64,
	0x73, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x64, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x64, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x53,
	0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x4d, 0x4f,
	0x56, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x22, 0x98, 0x01, 0x0a, 0x18, 0x53, 0x43, 0x32, 0x53, 0x5f,
	0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f,
	0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d,
	0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f,
	0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x1a, 0x0a, 0x18, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54,
	0x4f, 0x52, 0x59, 0x5f, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x22, 0x9e, 0x01,
	0x0a, 0x17, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x57, 0x41, 0x50,
	0x5f, 0x44, 0x53, 0x54, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52,
	0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52,
	0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x53,
	0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x77,
	0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0xd9,
	0x01, 0x0a, 0x17, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52,
	0x59, 0x5f, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x72,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f,
	0x52, 0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f,
	0x52, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x73, 0x74,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52,
	0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52,
	0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40, 0x0a, 0x09, 0x73, 0x77, 0x61, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x44, 0x43,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52,
	0x59, 0x5f, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x44, 0x53, 0x54, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52,
	0x09, 0x73, 0x77, 0x61, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x19, 0x0a, 0x17, 0x53, 0x53,
	0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x57, 0x41,
	0x50, 0x5f, 0x52, 0x45, 0x53, 0x22, 0xba, 0x01, 0x0a, 0x1d, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49,
	0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x4d,
	0x4f, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f,
	0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x73,
	0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x64, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x73, 0x74, 0x53, 0x6c, 0x6f, 0x74,
	0x49, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45,
	0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x4d, 0x4f, 0x56, 0x45,
	0x5f, 0x52, 0x45, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x55, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x55, 0x6e,
	0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0xb4, 0x01, 0x0a,
	0x1e, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f,
	0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x4d, 0x45, 0x52, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x12,
	0x3d, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e,
	0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d,
	0x0a, 0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56,
	0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x20, 0x0a, 0x1e, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45,
	0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x4d, 0x45, 0x52, 0x47,
	0x45, 0x5f, 0x52, 0x45, 0x53, 0x22, 0xf9, 0x01, 0x0a, 0x1d, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49,
	0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x53,
	0x57, 0x41, 0x50, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x72, 0x63, 0x49, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f,
	0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x73,
	0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x49,
	0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07, 0x64, 0x73,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x6e, 0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x77,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0e, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49,
	0x64, 0x22, 0x87, 0x01, 0x0a, 0x1d, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e,
	0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x50, 0x4c, 0x49, 0x54, 0x5f, 0x53, 0x57, 0x41, 0x50, 0x5f,
	0x52, 0x45, 0x53, 0x12, 0x20, 0x0a, 0x0b, 0x6e, 0x65, 0x77, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x6e, 0x65, 0x77, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e,
	0x65, 0x77, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x22, 0xef, 0x01, 0x0a, 0x29,
	0x53, 0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x54,
	0x57, 0x4f, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x45, 0x44, 0x5f, 0x57, 0x45, 0x41, 0x50, 0x4f, 0x4e,
	0x5f, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x3d, 0x0a, 0x07, 0x73, 0x72, 0x63,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52,
	0x59, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52,
	0x07, 0x73, 0x72, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3d, 0x0a, 0x07, 0x64, 0x73, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x44, 0x43, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59,
	0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x52, 0x45, 0x51, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x52, 0x07,
	0x64, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x6c,
	0x6f, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53,
	0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x6e, 0x65, 0x77, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x6e,
	0x65, 0x77, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x2b, 0x0a,
	0x29, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f,
	0x54, 0x57, 0x4f, 0x5f, 0x48, 0x41, 0x4e, 0x44, 0x45, 0x44, 0x5f, 0x57, 0x45, 0x41, 0x50, 0x4f,
	0x4e, 0x5f, 0x53, 0x57, 0x41, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x22, 0xa6, 0x01, 0x0a, 0x20, 0x53,
	0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x49,
	0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x12,
	0x2a, 0x0a, 0x10, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10, 0x73, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x2a, 0x0a, 0x07, 0x6f,
	0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44,
	0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07,
	0x6f, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x07, 0x6e, 0x65, 0x77, 0x49, 0x74,
	0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x07, 0x6e, 0x65, 0x77, 0x49,
	0x74, 0x65, 0x6d, 0x22, 0xa9, 0x02, 0x0a, 0x20, 0x53, 0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56,
	0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x55, 0x50,
	0x44, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2a, 0x0a, 0x07, 0x6f, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x07, 0x6f, 0x6c, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x2a, 0x0a, 0x07,
	0x6e, 0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52,
	0x07, 0x6e, 0x65, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x94, 0x01, 0x0a, 0x1e, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x53, 0x49,
	0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x41, 0x49, 0x4c, 0x5f,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x4f, 0x4c, 0x44, 0x5f,
	0x49, 0x54, 0x45, 0x4d, 0x10, 0x03, 0x12, 0x1d, 0x0a, 0x19, 0x46, 0x41, 0x49, 0x4c, 0x5f, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x4e, 0x45, 0x57, 0x5f, 0x49,
	0x54, 0x45, 0x4d, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x41, 0x49, 0x4c, 0x5f, 0x43, 0x48,
	0x45, 0x43, 0x4b, 0x5f, 0x4c, 0x4f, 0x47, 0x49, 0x43, 0x5f, 0x4c, 0x4f, 0x47, 0x10, 0x05, 0x22,
	0x35, 0x0a, 0x15, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f,
	0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x51, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x52, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x73, 0x52,
	0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x22, 0xb5, 0x01, 0x0a, 0x15, 0x53, 0x53, 0x32, 0x43, 0x5f,
	0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x5f, 0x52, 0x45, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x34, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x0c, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x4e,
	0x0a, 0x13, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45,
	0x5f, 0x49, 0x4e, 0x46, 0x4f, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x4f, 0x4b, 0x5f, 0x53, 0x45, 0x4e, 0x44, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x4f, 0x4b, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x43, 0x48, 0x41, 0x4e,
	0x47, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x03, 0x22, 0x4b,
	0x0a, 0x21, 0x53, 0x43, 0x32, 0x53, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59,
	0x5f, 0x45, 0x58, 0x50, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f,
	0x52, 0x45, 0x51, 0x12, 0x26, 0x0a, 0x0e, 0x62, 0x75, 0x79, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x62, 0x75, 0x79,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x21, 0x53,
	0x53, 0x32, 0x43, 0x5f, 0x49, 0x4e, 0x56, 0x45, 0x4e, 0x54, 0x4f, 0x52, 0x59, 0x5f, 0x45, 0x58,
	0x50, 0x41, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x52, 0x45, 0x53,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x3b, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x42, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x50, 0x00, 0x5a, 0x15,
	0x64, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Inventory_proto_rawDescOnce sync.Once
	file_Inventory_proto_rawDescData = file_Inventory_proto_rawDesc
)

func file_Inventory_proto_rawDescGZIP() []byte {
	file_Inventory_proto_rawDescOnce.Do(func() {
		file_Inventory_proto_rawDescData = protoimpl.X.CompressGZIP(file_Inventory_proto_rawDescData)
	})
	return file_Inventory_proto_rawDescData
}

var file_Inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_Inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_Inventory_proto_goTypes = []interface{}{
	(SS2C_INVENTORY_INFO_RES_RESULT_INVENTORY_INFO_INFO)(0),              // 0: DC.Packet.SS2C_INVENTORY_INFO_RES.RESULT_INVENTORY_INFO_INFO
	(SS2C_INVENTORY_ALL_UPDATE_RES_RESULT_INVENTORY_UPDATE)(0),           // 1: DC.Packet.SS2C_INVENTORY_ALL_UPDATE_RES.RESULT_INVENTORY_UPDATE
	(SS2C_INVENTORY_SINGLE_UPDATE_RES_RESULT_INVENTORY_SINGLE_UPDATE)(0), // 2: DC.Packet.SS2C_INVENTORY_SINGLE_UPDATE_RES.RESULT_INVENTORY_SINGLE_UPDATE
	(SS2C_STORAGE_INFO_RES_RESULT_STORAGE_INFO)(0),                       // 3: DC.Packet.SS2C_STORAGE_INFO_RES.RESULT_STORAGE_INFO
	(*SINVENTORY_REQUEST_INFO)(nil),                                      // 4: DC.Packet.SINVENTORY_REQUEST_INFO
	(*SINVENTORY_RESULT_INFO)(nil),                                       // 5: DC.Packet.SINVENTORY_RESULT_INFO
	(*SC2S_INVENTORY_INFO_REQ)(nil),                                      // 6: DC.Packet.SC2S_INVENTORY_INFO_REQ
	(*SS2C_INVENTORY_INFO_RES)(nil),                                      // 7: DC.Packet.SS2C_INVENTORY_INFO_RES
	(*SC2S_INVENTORY_ALL_UPDATE_REQ)(nil),                                // 8: DC.Packet.SC2S_INVENTORY_ALL_UPDATE_REQ
	(*SS2C_INVENTORY_ALL_UPDATE_RES)(nil),                                // 9: DC.Packet.SS2C_INVENTORY_ALL_UPDATE_RES
	(*SINVENTORY_ITEM_REQ_INFO)(nil),                                     // 10: DC.Packet.SINVENTORY_ITEM_REQ_INFO
	(*SC2S_INVENTORY_MOVE_REQ)(nil),                                      // 11: DC.Packet.SC2S_INVENTORY_MOVE_REQ
	(*SS2C_INVENTORY_MOVE_RES)(nil),                                      // 12: DC.Packet.SS2C_INVENTORY_MOVE_RES
	(*SC2S_INVENTORY_MERGE_REQ)(nil),                                     // 13: DC.Packet.SC2S_INVENTORY_MERGE_REQ
	(*SS2C_INVENTORY_MERGE_RES)(nil),                                     // 14: DC.Packet.SS2C_INVENTORY_MERGE_RES
	(*INVENTORY_SWAP_DST_INFO)(nil),                                      // 15: DC.Packet.INVENTORY_SWAP_DST_INFO
	(*SC2S_INVENTORY_SWAP_REQ)(nil),                                      // 16: DC.Packet.SC2S_INVENTORY_SWAP_REQ
	(*SS2C_INVENTORY_SWAP_RES)(nil),                                      // 17: DC.Packet.SS2C_INVENTORY_SWAP_RES
	(*SC2S_INVENTORY_SPLIT_MOVE_REQ)(nil),                                // 18: DC.Packet.SC2S_INVENTORY_SPLIT_MOVE_REQ
	(*SS2C_INVENTORY_SPLIT_MOVE_RES)(nil),                                // 19: DC.Packet.SS2C_INVENTORY_SPLIT_MOVE_RES
	(*SC2S_INVENTORY_SPLIT_MERGE_REQ)(nil),                               // 20: DC.Packet.SC2S_INVENTORY_SPLIT_MERGE_REQ
	(*SS2C_INVENTORY_SPLIT_MERGE_RES)(nil),                               // 21: DC.Packet.SS2C_INVENTORY_SPLIT_MERGE_RES
	(*SC2S_INVENTORY_SPLIT_SWAP_REQ)(nil),                                // 22: DC.Packet.SC2S_INVENTORY_SPLIT_SWAP_REQ
	(*SS2C_INVENTORY_SPLIT_SWAP_RES)(nil),                                // 23: DC.Packet.SS2C_INVENTORY_SPLIT_SWAP_RES
	(*SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ)(nil),                    // 24: DC.Packet.SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ
	(*SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES)(nil),                    // 25: DC.Packet.SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES
	(*SC2S_INVENTORY_SINGLE_UPDATE_REQ)(nil),                             // 26: DC.Packet.SC2S_INVENTORY_SINGLE_UPDATE_REQ
	(*SS2C_INVENTORY_SINGLE_UPDATE_RES)(nil),                             // 27: DC.Packet.SS2C_INVENTORY_SINGLE_UPDATE_RES
	(*SC2S_STORAGE_INFO_REQ)(nil),                                        // 28: DC.Packet.SC2S_STORAGE_INFO_REQ
	(*SS2C_STORAGE_INFO_RES)(nil),                                        // 29: DC.Packet.SS2C_STORAGE_INFO_RES
	(*SC2S_INVENTORY_EXPAND_STORAGE_REQ)(nil),                            // 30: DC.Packet.SC2S_INVENTORY_EXPAND_STORAGE_REQ
	(*SS2C_INVENTORY_EXPAND_STORAGE_RES)(nil),                            // 31: DC.Packet.SS2C_INVENTORY_EXPAND_STORAGE_RES
	(*SItem)(nil), // 32: DC.Packet.SItem
}
var file_Inventory_proto_depIdxs = []int32{
	32, // 0: DC.Packet.SINVENTORY_RESULT_INFO.insertItems:type_name -> DC.Packet.SItem
	32, // 1: DC.Packet.SINVENTORY_RESULT_INFO.updateItems:type_name -> DC.Packet.SItem
	32, // 2: DC.Packet.SS2C_INVENTORY_INFO_RES.inventoryItems:type_name -> DC.Packet.SItem
	32, // 3: DC.Packet.SC2S_INVENTORY_ALL_UPDATE_REQ.inventoryItems:type_name -> DC.Packet.SItem
	32, // 4: DC.Packet.SS2C_INVENTORY_ALL_UPDATE_RES.inventoryItems:type_name -> DC.Packet.SItem
	10, // 5: DC.Packet.SC2S_INVENTORY_MOVE_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 6: DC.Packet.SC2S_INVENTORY_MERGE_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 7: DC.Packet.SC2S_INVENTORY_MERGE_REQ.dstInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 8: DC.Packet.INVENTORY_SWAP_DST_INFO.dstInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 9: DC.Packet.SC2S_INVENTORY_SWAP_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 10: DC.Packet.SC2S_INVENTORY_SWAP_REQ.dstInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	15, // 11: DC.Packet.SC2S_INVENTORY_SWAP_REQ.swapInfos:type_name -> DC.Packet.INVENTORY_SWAP_DST_INFO
	10, // 12: DC.Packet.SC2S_INVENTORY_SPLIT_MOVE_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 13: DC.Packet.SC2S_INVENTORY_SPLIT_MERGE_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 14: DC.Packet.SC2S_INVENTORY_SPLIT_MERGE_REQ.dstInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 15: DC.Packet.SC2S_INVENTORY_SPLIT_SWAP_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 16: DC.Packet.SC2S_INVENTORY_SPLIT_SWAP_REQ.dstInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 17: DC.Packet.SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ.srcInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	10, // 18: DC.Packet.SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ.dstInfo:type_name -> DC.Packet.SINVENTORY_ITEM_REQ_INFO
	32, // 19: DC.Packet.SC2S_INVENTORY_SINGLE_UPDATE_REQ.oldItem:type_name -> DC.Packet.SItem
	32, // 20: DC.Packet.SC2S_INVENTORY_SINGLE_UPDATE_REQ.newItem:type_name -> DC.Packet.SItem
	32, // 21: DC.Packet.SS2C_INVENTORY_SINGLE_UPDATE_RES.oldItem:type_name -> DC.Packet.SItem
	32, // 22: DC.Packet.SS2C_INVENTORY_SINGLE_UPDATE_RES.newItem:type_name -> DC.Packet.SItem
	32, // 23: DC.Packet.SS2C_STORAGE_INFO_RES.storageItems:type_name -> DC.Packet.SItem
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_Inventory_proto_init() }
func file_Inventory_proto_init() {
	if File_Inventory_proto != nil {
		return
	}
	file___Item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Inventory_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SINVENTORY_REQUEST_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SINVENTORY_RESULT_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_INFO_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_INFO_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_ALL_UPDATE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_ALL_UPDATE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SINVENTORY_ITEM_REQ_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_MOVE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_MOVE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_MERGE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_MERGE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*INVENTORY_SWAP_DST_INFO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_SWAP_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_SWAP_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_SPLIT_MOVE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_SPLIT_MOVE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_SPLIT_MERGE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_SPLIT_MERGE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_SPLIT_SWAP_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_SPLIT_SWAP_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_SINGLE_UPDATE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_SINGLE_UPDATE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_STORAGE_INFO_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_STORAGE_INFO_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SC2S_INVENTORY_EXPAND_STORAGE_REQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Inventory_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SS2C_INVENTORY_EXPAND_STORAGE_RES); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Inventory_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Inventory_proto_goTypes,
		DependencyIndexes: file_Inventory_proto_depIdxs,
		EnumInfos:         file_Inventory_proto_enumTypes,
		MessageInfos:      file_Inventory_proto_msgTypes,
	}.Build()
	File_Inventory_proto = out.File
	file_Inventory_proto_rawDesc = nil
	file_Inventory_proto_goTypes = nil
	file_Inventory_proto_depIdxs = nil
}
