// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: _Item.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SItemMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SoulHeart_AccountId         string `protobuf:"bytes,1,opt,name=SoulHeart_AccountId,json=SoulHeartAccountId,proto3" json:"SoulHeart_AccountId,omitempty"`
	SoulHeart_PartyId           string `protobuf:"bytes,2,opt,name=SoulHeart_PartyId,json=SoulHeartPartyId,proto3" json:"SoulHeart_PartyId,omitempty"`
	SoulHeart_NickNameOrigin    string `protobuf:"bytes,3,opt,name=SoulHeart_NickName_origin,json=SoulHeartNickNameOrigin,proto3" json:"SoulHeart_NickName_origin,omitempty"`
	SoulHeart_NickNameStreaming string `protobuf:"bytes,4,opt,name=SoulHeart_NickName_streaming,json=SoulHeartNickNameStreaming,proto3" json:"SoulHeart_NickName_streaming,omitempty"`
	SoulHeart_ItemSkinId        string `protobuf:"bytes,5,opt,name=SoulHeart_ItemSkinId,json=SoulHeartItemSkinId,proto3" json:"SoulHeart_ItemSkinId,omitempty"`
	AvailableValue              uint32 `protobuf:"varint,6,opt,name=AvailableValue,proto3" json:"AvailableValue,omitempty"`
}

func (x *SItemMeta) Reset() {
	*x = SItemMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemMeta) ProtoMessage() {}

func (x *SItemMeta) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemMeta.ProtoReflect.Descriptor instead.
func (*SItemMeta) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{0}
}

func (x *SItemMeta) GetSoulHeart_AccountId() string {
	if x != nil {
		return x.SoulHeart_AccountId
	}
	return ""
}

func (x *SItemMeta) GetSoulHeart_PartyId() string {
	if x != nil {
		return x.SoulHeart_PartyId
	}
	return ""
}

func (x *SItemMeta) GetSoulHeart_NickNameOrigin() string {
	if x != nil {
		return x.SoulHeart_NickNameOrigin
	}
	return ""
}

func (x *SItemMeta) GetSoulHeart_NickNameStreaming() string {
	if x != nil {
		return x.SoulHeart_NickNameStreaming
	}
	return ""
}

func (x *SItemMeta) GetSoulHeart_ItemSkinId() string {
	if x != nil {
		return x.SoulHeart_ItemSkinId
	}
	return ""
}

func (x *SItemMeta) GetAvailableValue() uint32 {
	if x != nil {
		return x.AvailableValue
	}
	return 0
}

type SItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemUniqueId               uint64              `protobuf:"varint,1,opt,name=itemUniqueId,proto3" json:"itemUniqueId,omitempty"`
	ItemId                     string              `protobuf:"bytes,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemCount                  uint32              `protobuf:"varint,3,opt,name=itemCount,proto3" json:"itemCount,omitempty"`
	InventoryId                uint32              `protobuf:"varint,4,opt,name=inventoryId,proto3" json:"inventoryId,omitempty"`
	SlotId                     uint32              `protobuf:"varint,5,opt,name=slotId,proto3" json:"slotId,omitempty"`
	ItemAmmoCount              uint32              `protobuf:"varint,7,opt,name=itemAmmoCount,proto3" json:"itemAmmoCount,omitempty"`
	ItemContentsCount          uint32              `protobuf:"varint,8,opt,name=itemContentsCount,proto3" json:"itemContentsCount,omitempty"`
	PrimaryPropertyArray       []*SItemProperty    `protobuf:"bytes,9,rep,name=primaryPropertyArray,proto3" json:"primaryPropertyArray,omitempty"`
	SecondaryPropertyArray     []*SItemProperty    `protobuf:"bytes,10,rep,name=secondaryPropertyArray,proto3" json:"secondaryPropertyArray,omitempty"`
	LootState                  int32               `protobuf:"varint,11,opt,name=lootState,proto3" json:"lootState,omitempty"`
	OriginType                 int32               `protobuf:"varint,12,opt,name=originType,proto3" json:"originType,omitempty"`
	OriginNickName             string              `protobuf:"bytes,13,opt,name=originNickName,proto3" json:"originNickName,omitempty"`
	OriginSteamingModeNickName string              `protobuf:"bytes,14,opt,name=originSteamingModeNickName,proto3" json:"originSteamingModeNickName,omitempty"`
	SecondaryEnchantArray      []*SItemEnchantInfo `protobuf:"bytes,15,rep,name=secondaryEnchantArray,proto3" json:"secondaryEnchantArray,omitempty"`
	Tradable                   int32               `protobuf:"varint,16,opt,name=tradable,proto3" json:"tradable,omitempty"`
	PermittedAreaArray         []*SItemPermitted   `protobuf:"bytes,17,rep,name=permittedAreaArray,proto3" json:"permittedAreaArray,omitempty"`
}

func (x *SItem) Reset() {
	*x = SItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItem) ProtoMessage() {}

func (x *SItem) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItem.ProtoReflect.Descriptor instead.
func (*SItem) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{1}
}

func (x *SItem) GetItemUniqueId() uint64 {
	if x != nil {
		return x.ItemUniqueId
	}
	return 0
}

func (x *SItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *SItem) GetItemCount() uint32 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *SItem) GetInventoryId() uint32 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *SItem) GetSlotId() uint32 {
	if x != nil {
		return x.SlotId
	}
	return 0
}

func (x *SItem) GetItemAmmoCount() uint32 {
	if x != nil {
		return x.ItemAmmoCount
	}
	return 0
}

func (x *SItem) GetItemContentsCount() uint32 {
	if x != nil {
		return x.ItemContentsCount
	}
	return 0
}

func (x *SItem) GetPrimaryPropertyArray() []*SItemProperty {
	if x != nil {
		return x.PrimaryPropertyArray
	}
	return nil
}

func (x *SItem) GetSecondaryPropertyArray() []*SItemProperty {
	if x != nil {
		return x.SecondaryPropertyArray
	}
	return nil
}

func (x *SItem) GetLootState() int32 {
	if x != nil {
		return x.LootState
	}
	return 0
}

func (x *SItem) GetOriginType() int32 {
	if x != nil {
		return x.OriginType
	}
	return 0
}

func (x *SItem) GetOriginNickName() string {
	if x != nil {
		return x.OriginNickName
	}
	return ""
}

func (x *SItem) GetOriginSteamingModeNickName() string {
	if x != nil {
		return x.OriginSteamingModeNickName
	}
	return ""
}

func (x *SItem) GetSecondaryEnchantArray() []*SItemEnchantInfo {
	if x != nil {
		return x.SecondaryEnchantArray
	}
	return nil
}

func (x *SItem) GetTradable() int32 {
	if x != nil {
		return x.Tradable
	}
	return 0
}

func (x *SItem) GetPermittedAreaArray() []*SItemPermitted {
	if x != nil {
		return x.PermittedAreaArray
	}
	return nil
}

type SItemProperties struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Properties []*SItemProperty `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty"`
}

func (x *SItemProperties) Reset() {
	*x = SItemProperties{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemProperties) ProtoMessage() {}

func (x *SItemProperties) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemProperties.ProtoReflect.Descriptor instead.
func (*SItemProperties) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{2}
}

func (x *SItemProperties) GetProperties() []*SItemProperty {
	if x != nil {
		return x.Properties
	}
	return nil
}

type SItemProperty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyTypeId string `protobuf:"bytes,1,opt,name=propertyTypeId,proto3" json:"propertyTypeId,omitempty"`
	PropertyValue  int32  `protobuf:"varint,2,opt,name=propertyValue,proto3" json:"propertyValue,omitempty"`
}

func (x *SItemProperty) Reset() {
	*x = SItemProperty{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemProperty) ProtoMessage() {}

func (x *SItemProperty) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemProperty.ProtoReflect.Descriptor instead.
func (*SItemProperty) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{3}
}

func (x *SItemProperty) GetPropertyTypeId() string {
	if x != nil {
		return x.PropertyTypeId
	}
	return ""
}

func (x *SItemProperty) GetPropertyValue() int32 {
	if x != nil {
		return x.PropertyValue
	}
	return 0
}

type SItemEnchantInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PropertyIndex  uint32 `protobuf:"varint,1,opt,name=propertyIndex,proto3" json:"propertyIndex,omitempty"`
	MaterialItemId string `protobuf:"bytes,2,opt,name=materialItemId,proto3" json:"materialItemId,omitempty"`
}

func (x *SItemEnchantInfo) Reset() {
	*x = SItemEnchantInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemEnchantInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemEnchantInfo) ProtoMessage() {}

func (x *SItemEnchantInfo) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemEnchantInfo.ProtoReflect.Descriptor instead.
func (*SItemEnchantInfo) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{4}
}

func (x *SItemEnchantInfo) GetPropertyIndex() uint32 {
	if x != nil {
		return x.PropertyIndex
	}
	return 0
}

func (x *SItemEnchantInfo) GetMaterialItemId() string {
	if x != nil {
		return x.MaterialItemId
	}
	return ""
}

type SItemEnchantInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EnchantInfos []*SItemEnchantInfo `protobuf:"bytes,1,rep,name=enchantInfos,proto3" json:"enchantInfos,omitempty"`
}

func (x *SItemEnchantInfos) Reset() {
	*x = SItemEnchantInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemEnchantInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemEnchantInfos) ProtoMessage() {}

func (x *SItemEnchantInfos) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemEnchantInfos.ProtoReflect.Descriptor instead.
func (*SItemEnchantInfos) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{5}
}

func (x *SItemEnchantInfos) GetEnchantInfos() []*SItemEnchantInfo {
	if x != nil {
		return x.EnchantInfos
	}
	return nil
}

type SItemPermittedInfos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermittedList []*SItemPermitted `protobuf:"bytes,1,rep,name=permittedList,proto3" json:"permittedList,omitempty"`
}

func (x *SItemPermittedInfos) Reset() {
	*x = SItemPermittedInfos{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemPermittedInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemPermittedInfos) ProtoMessage() {}

func (x *SItemPermittedInfos) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemPermittedInfos.ProtoReflect.Descriptor instead.
func (*SItemPermittedInfos) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{6}
}

func (x *SItemPermittedInfos) GetPermittedList() []*SItemPermitted {
	if x != nil {
		return x.PermittedList
	}
	return nil
}

type SItemPermitted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *SItemPermitted) Reset() {
	*x = SItemPermitted{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItemPermitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItemPermitted) ProtoMessage() {}

func (x *SItemPermitted) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItemPermitted.ProtoReflect.Descriptor instead.
func (*SItemPermitted) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{7}
}

func (x *SItemPermitted) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type SItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*SItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *SItems) Reset() {
	*x = SItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SItems) ProtoMessage() {}

func (x *SItems) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SItems.ProtoReflect.Descriptor instead.
func (*SItems) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{8}
}

func (x *SItems) GetItem() []*SItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type SPerk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	PerkId string `protobuf:"bytes,2,opt,name=perkId,proto3" json:"perkId,omitempty"`
}

func (x *SPerk) Reset() {
	*x = SPerk{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPerk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPerk) ProtoMessage() {}

func (x *SPerk) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPerk.ProtoReflect.Descriptor instead.
func (*SPerk) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{9}
}

func (x *SPerk) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SPerk) GetPerkId() string {
	if x != nil {
		return x.PerkId
	}
	return ""
}

type SSkill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	SkillId string `protobuf:"bytes,2,opt,name=skillId,proto3" json:"skillId,omitempty"`
}

func (x *SSkill) Reset() {
	*x = SSkill{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSkill) ProtoMessage() {}

func (x *SSkill) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSkill.ProtoReflect.Descriptor instead.
func (*SSkill) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{10}
}

func (x *SSkill) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *SSkill) GetSkillId() string {
	if x != nil {
		return x.SkillId
	}
	return ""
}

type SSpell struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotIndex     uint32 `protobuf:"varint,1,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`
	SequenceIndex uint32 `protobuf:"varint,2,opt,name=sequenceIndex,proto3" json:"sequenceIndex,omitempty"`
	SpellId       string `protobuf:"bytes,3,opt,name=spellId,proto3" json:"spellId,omitempty"`
}

func (x *SSpell) Reset() {
	*x = SSpell{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSpell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSpell) ProtoMessage() {}

func (x *SSpell) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSpell.ProtoReflect.Descriptor instead.
func (*SSpell) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{11}
}

func (x *SSpell) GetSlotIndex() uint32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *SSpell) GetSequenceIndex() uint32 {
	if x != nil {
		return x.SequenceIndex
	}
	return 0
}

func (x *SSpell) GetSpellId() string {
	if x != nil {
		return x.SpellId
	}
	return ""
}

type SMusic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MusicId       string `protobuf:"bytes,1,opt,name=musicId,proto3" json:"musicId,omitempty"`
	SlotIndex     uint32 `protobuf:"varint,2,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`
	SequenceIndex uint32 `protobuf:"varint,3,opt,name=sequenceIndex,proto3" json:"sequenceIndex,omitempty"`
}

func (x *SMusic) Reset() {
	*x = SMusic{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SMusic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMusic) ProtoMessage() {}

func (x *SMusic) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMusic.ProtoReflect.Descriptor instead.
func (*SMusic) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{12}
}

func (x *SMusic) GetMusicId() string {
	if x != nil {
		return x.MusicId
	}
	return ""
}

func (x *SMusic) GetSlotIndex() uint32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *SMusic) GetSequenceIndex() uint32 {
	if x != nil {
		return x.SequenceIndex
	}
	return 0
}

type SShapeShift struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShapeShiftId  string `protobuf:"bytes,1,opt,name=shapeShiftId,proto3" json:"shapeShiftId,omitempty"`
	SlotIndex     uint32 `protobuf:"varint,2,opt,name=slotIndex,proto3" json:"slotIndex,omitempty"`
	SequenceIndex uint32 `protobuf:"varint,3,opt,name=sequenceIndex,proto3" json:"sequenceIndex,omitempty"`
}

func (x *SShapeShift) Reset() {
	*x = SShapeShift{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SShapeShift) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SShapeShift) ProtoMessage() {}

func (x *SShapeShift) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SShapeShift.ProtoReflect.Descriptor instead.
func (*SShapeShift) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{13}
}

func (x *SShapeShift) GetShapeShiftId() string {
	if x != nil {
		return x.ShapeShiftId
	}
	return ""
}

func (x *SShapeShift) GetSlotIndex() uint32 {
	if x != nil {
		return x.SlotIndex
	}
	return 0
}

func (x *SShapeShift) GetSequenceIndex() uint32 {
	if x != nil {
		return x.SequenceIndex
	}
	return 0
}

type SCUSTOMIZE_CHARACTER struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomizeCharacterId string `protobuf:"bytes,1,opt,name=customizeCharacterId,proto3" json:"customizeCharacterId,omitempty"`
	IsEquip              int32  `protobuf:"varint,2,opt,name=isEquip,proto3" json:"isEquip,omitempty"`
	IsNew                int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_CHARACTER) Reset() {
	*x = SCUSTOMIZE_CHARACTER{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_CHARACTER) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_CHARACTER) ProtoMessage() {}

func (x *SCUSTOMIZE_CHARACTER) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_CHARACTER.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_CHARACTER) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{14}
}

func (x *SCUSTOMIZE_CHARACTER) GetCustomizeCharacterId() string {
	if x != nil {
		return x.CustomizeCharacterId
	}
	return ""
}

func (x *SCUSTOMIZE_CHARACTER) GetIsEquip() int32 {
	if x != nil {
		return x.IsEquip
	}
	return 0
}

func (x *SCUSTOMIZE_CHARACTER) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SCUSTOMIZE_ITEM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomizeItemId string `protobuf:"bytes,1,opt,name=customizeItemId,proto3" json:"customizeItemId,omitempty"`
	IsEquip         int32  `protobuf:"varint,2,opt,name=isEquip,proto3" json:"isEquip,omitempty"`
	IsNew           int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_ITEM) Reset() {
	*x = SCUSTOMIZE_ITEM{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_ITEM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_ITEM) ProtoMessage() {}

func (x *SCUSTOMIZE_ITEM) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_ITEM.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_ITEM) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{15}
}

func (x *SCUSTOMIZE_ITEM) GetCustomizeItemId() string {
	if x != nil {
		return x.CustomizeItemId
	}
	return ""
}

func (x *SCUSTOMIZE_ITEM) GetIsEquip() int32 {
	if x != nil {
		return x.IsEquip
	}
	return 0
}

func (x *SCUSTOMIZE_ITEM) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SCUSTOMIZE_ARMOR_SKIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomizeArmorSkinId string `protobuf:"bytes,1,opt,name=customizeArmorSkinId,proto3" json:"customizeArmorSkinId,omitempty"`
	IsEquip              int32  `protobuf:"varint,2,opt,name=isEquip,proto3" json:"isEquip,omitempty"`
	IsNew                int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_ARMOR_SKIN) Reset() {
	*x = SCUSTOMIZE_ARMOR_SKIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_ARMOR_SKIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_ARMOR_SKIN) ProtoMessage() {}

func (x *SCUSTOMIZE_ARMOR_SKIN) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_ARMOR_SKIN.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_ARMOR_SKIN) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{16}
}

func (x *SCUSTOMIZE_ARMOR_SKIN) GetCustomizeArmorSkinId() string {
	if x != nil {
		return x.CustomizeArmorSkinId
	}
	return ""
}

func (x *SCUSTOMIZE_ARMOR_SKIN) GetIsEquip() int32 {
	if x != nil {
		return x.IsEquip
	}
	return 0
}

func (x *SCUSTOMIZE_ARMOR_SKIN) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SEMOTE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmoteId        string `protobuf:"bytes,1,opt,name=emoteId,proto3" json:"emoteId,omitempty"`
	EquipSlotIndex int32  `protobuf:"varint,2,opt,name=equipSlotIndex,proto3" json:"equipSlotIndex,omitempty"`
	IsNew          int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SEMOTE) Reset() {
	*x = SEMOTE{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SEMOTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SEMOTE) ProtoMessage() {}

func (x *SEMOTE) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SEMOTE.ProtoReflect.Descriptor instead.
func (*SEMOTE) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{17}
}

func (x *SEMOTE) GetEmoteId() string {
	if x != nil {
		return x.EmoteId
	}
	return ""
}

func (x *SEMOTE) GetEquipSlotIndex() int32 {
	if x != nil {
		return x.EquipSlotIndex
	}
	return 0
}

func (x *SEMOTE) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SCUSTOMIZE_ACTION struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomizeActionId string `protobuf:"bytes,1,opt,name=customizeActionId,proto3" json:"customizeActionId,omitempty"`
	IsEquip           int32  `protobuf:"varint,2,opt,name=isEquip,proto3" json:"isEquip,omitempty"`
	IsNew             int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_ACTION) Reset() {
	*x = SCUSTOMIZE_ACTION{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_ACTION) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_ACTION) ProtoMessage() {}

func (x *SCUSTOMIZE_ACTION) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_ACTION.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_ACTION) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{18}
}

func (x *SCUSTOMIZE_ACTION) GetCustomizeActionId() string {
	if x != nil {
		return x.CustomizeActionId
	}
	return ""
}

func (x *SCUSTOMIZE_ACTION) GetIsEquip() int32 {
	if x != nil {
		return x.IsEquip
	}
	return 0
}

func (x *SCUSTOMIZE_ACTION) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SCUSTOMIZE_LOBBY_EMOTE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbyEmoteId   string `protobuf:"bytes,1,opt,name=lobbyEmoteId,proto3" json:"lobbyEmoteId,omitempty"`
	EquipSlotIndex int32  `protobuf:"varint,2,opt,name=equipSlotIndex,proto3" json:"equipSlotIndex,omitempty"`
	IsNew          int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_LOBBY_EMOTE) Reset() {
	*x = SCUSTOMIZE_LOBBY_EMOTE{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_LOBBY_EMOTE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_LOBBY_EMOTE) ProtoMessage() {}

func (x *SCUSTOMIZE_LOBBY_EMOTE) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_LOBBY_EMOTE.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_LOBBY_EMOTE) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{19}
}

func (x *SCUSTOMIZE_LOBBY_EMOTE) GetLobbyEmoteId() string {
	if x != nil {
		return x.LobbyEmoteId
	}
	return ""
}

func (x *SCUSTOMIZE_LOBBY_EMOTE) GetEquipSlotIndex() int32 {
	if x != nil {
		return x.EquipSlotIndex
	}
	return 0
}

func (x *SCUSTOMIZE_LOBBY_EMOTE) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SCUSTOMIZE_LOBBY_SKIN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LobbySkinId string `protobuf:"bytes,1,opt,name=lobbySkinId,proto3" json:"lobbySkinId,omitempty"`
	IsEquip     int32  `protobuf:"varint,2,opt,name=isEquip,proto3" json:"isEquip,omitempty"`
	IsNew       int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_LOBBY_SKIN) Reset() {
	*x = SCUSTOMIZE_LOBBY_SKIN{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_LOBBY_SKIN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_LOBBY_SKIN) ProtoMessage() {}

func (x *SCUSTOMIZE_LOBBY_SKIN) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_LOBBY_SKIN.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_LOBBY_SKIN) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{20}
}

func (x *SCUSTOMIZE_LOBBY_SKIN) GetLobbySkinId() string {
	if x != nil {
		return x.LobbySkinId
	}
	return ""
}

func (x *SCUSTOMIZE_LOBBY_SKIN) GetIsEquip() int32 {
	if x != nil {
		return x.IsEquip
	}
	return 0
}

func (x *SCUSTOMIZE_LOBBY_SKIN) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SCUSTOMIZE_NAMEPLATE struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NameplateSkinId string `protobuf:"bytes,1,opt,name=nameplateSkinId,proto3" json:"nameplateSkinId,omitempty"`
	IsEquip         int32  `protobuf:"varint,2,opt,name=isEquip,proto3" json:"isEquip,omitempty"`
	IsNew           int32  `protobuf:"varint,3,opt,name=isNew,proto3" json:"isNew,omitempty"`
}

func (x *SCUSTOMIZE_NAMEPLATE) Reset() {
	*x = SCUSTOMIZE_NAMEPLATE{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SCUSTOMIZE_NAMEPLATE) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SCUSTOMIZE_NAMEPLATE) ProtoMessage() {}

func (x *SCUSTOMIZE_NAMEPLATE) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SCUSTOMIZE_NAMEPLATE.ProtoReflect.Descriptor instead.
func (*SCUSTOMIZE_NAMEPLATE) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{21}
}

func (x *SCUSTOMIZE_NAMEPLATE) GetNameplateSkinId() string {
	if x != nil {
		return x.NameplateSkinId
	}
	return ""
}

func (x *SCUSTOMIZE_NAMEPLATE) GetIsEquip() int32 {
	if x != nil {
		return x.IsEquip
	}
	return 0
}

func (x *SCUSTOMIZE_NAMEPLATE) GetIsNew() int32 {
	if x != nil {
		return x.IsNew
	}
	return 0
}

type SFriendItemRecoveryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendAccountId   string   `protobuf:"bytes,1,opt,name=friendAccountId,proto3" json:"friendAccountId,omitempty"`
	FriendCharacterId string   `protobuf:"bytes,2,opt,name=friendCharacterId,proto3" json:"friendCharacterId,omitempty"`
	RecoveryItemList  []*SItem `protobuf:"bytes,3,rep,name=recoveryItemList,proto3" json:"recoveryItemList,omitempty"`
}

func (x *SFriendItemRecoveryInfo) Reset() {
	*x = SFriendItemRecoveryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SFriendItemRecoveryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SFriendItemRecoveryInfo) ProtoMessage() {}

func (x *SFriendItemRecoveryInfo) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SFriendItemRecoveryInfo.ProtoReflect.Descriptor instead.
func (*SFriendItemRecoveryInfo) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{22}
}

func (x *SFriendItemRecoveryInfo) GetFriendAccountId() string {
	if x != nil {
		return x.FriendAccountId
	}
	return ""
}

func (x *SFriendItemRecoveryInfo) GetFriendCharacterId() string {
	if x != nil {
		return x.FriendCharacterId
	}
	return ""
}

func (x *SFriendItemRecoveryInfo) GetRecoveryItemList() []*SItem {
	if x != nil {
		return x.RecoveryItemList
	}
	return nil
}

type SGatheringHallItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin     *SItem  `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	PosX       float32 `protobuf:"fixed32,2,opt,name=posX,proto3" json:"posX,omitempty"`
	PosY       float32 `protobuf:"fixed32,3,opt,name=posY,proto3" json:"posY,omitempty"`
	PosZ       float32 `protobuf:"fixed32,4,opt,name=posZ,proto3" json:"posZ,omitempty"`
	RotPitch   float32 `protobuf:"fixed32,5,opt,name=rotPitch,proto3" json:"rotPitch,omitempty"`
	RotYaw     float32 `protobuf:"fixed32,6,opt,name=rotYaw,proto3" json:"rotYaw,omitempty"`
	RotRoll    float32 `protobuf:"fixed32,7,opt,name=rotRoll,proto3" json:"rotRoll,omitempty"`
	HallStatus int32   `protobuf:"varint,8,opt,name=hallStatus,proto3" json:"hallStatus,omitempty"`
}

func (x *SGatheringHallItem) Reset() {
	*x = SGatheringHallItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file___Item_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SGatheringHallItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SGatheringHallItem) ProtoMessage() {}

func (x *SGatheringHallItem) ProtoReflect() protoreflect.Message {
	mi := &file___Item_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SGatheringHallItem.ProtoReflect.Descriptor instead.
func (*SGatheringHallItem) Descriptor() ([]byte, []int) {
	return file___Item_proto_rawDescGZIP(), []int{23}
}

func (x *SGatheringHallItem) GetOrigin() *SItem {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *SGatheringHallItem) GetPosX() float32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *SGatheringHallItem) GetPosY() float32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *SGatheringHallItem) GetPosZ() float32 {
	if x != nil {
		return x.PosZ
	}
	return 0
}

func (x *SGatheringHallItem) GetRotPitch() float32 {
	if x != nil {
		return x.RotPitch
	}
	return 0
}

func (x *SGatheringHallItem) GetRotYaw() float32 {
	if x != nil {
		return x.RotYaw
	}
	return 0
}

func (x *SGatheringHallItem) GetRotRoll() float32 {
	if x != nil {
		return x.RotRoll
	}
	return 0
}

func (x *SGatheringHallItem) GetHallStatus() int32 {
	if x != nil {
		return x.HallStatus
	}
	return 0
}

var File___Item_proto protoreflect.FileDescriptor

var file___Item_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x5f, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x44,
	0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x22, 0xc2, 0x02, 0x0a, 0x09, 0x53, 0x49, 0x74,
	0x65, 0x6d, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x13, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x5f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x53, 0x6f, 0x75, 0x6c, 0x48,
	0x65, 0x61, 0x72, 0x74, 0x5f, 0x50, 0x61, 0x72, 0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x50, 0x61, 0x72,
	0x74, 0x79, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x19, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x5f, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x4f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x12, 0x40, 0x0a, 0x1c, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x5f, 0x4e, 0x69,
	0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72,
	0x74, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69,
	0x6e, 0x67, 0x12, 0x31, 0x0a, 0x14, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x5f,
	0x49, 0x74, 0x65, 0x6d, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x53, 0x6f, 0x75, 0x6c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x53,
	0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xef, 0x05,
	0x0a, 0x05, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x74, 0x65, 0x6d, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x69,
	0x74, 0x65, 0x6d, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65,
	0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72,
	0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x69,
	0x74, 0x65, 0x6d, 0x41, 0x6d, 0x6d, 0x6f, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0d, 0x69, 0x74, 0x65, 0x6d, 0x41, 0x6d, 0x6d, 0x6f, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2c, 0x0a, 0x11, 0x69, 0x74, 0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x11, 0x69, 0x74,
	0x65, 0x6d, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x4c, 0x0a, 0x14, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x14, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x50, 0x0a,
	0x16, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x52, 0x16, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x4e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3e, 0x0a, 0x1a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x53,
	0x74, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x4e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a, 0x6f, 0x72, 0x69, 0x67, 0x69,
	0x6e, 0x53, 0x74, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x4d, 0x6f, 0x64, 0x65, 0x4e, 0x69, 0x63,
	0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x51, 0x0a, 0x15, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61,
	0x72, 0x79, 0x45, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x0f,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x15, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x45, 0x6e, 0x63, 0x68,
	0x61, 0x6e, 0x74, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x74, 0x72, 0x61, 0x64,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x49, 0x0a, 0x12, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65,
	0x64, 0x41, 0x72, 0x65, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79, 0x18, 0x11, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74,
	0x65, 0x6d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x12, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x41, 0x72, 0x65, 0x61, 0x41, 0x72, 0x72, 0x61, 0x79, 0x22,
	0x4b, 0x0a, 0x0f, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x65, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x22, 0x5d, 0x0a, 0x0d,
	0x53, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x12, 0x26, 0x0a,
	0x0e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54,
	0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x60, 0x0a, 0x10, 0x53,
	0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x61, 0x74, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6d,
	0x61, 0x74, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x54, 0x0a,
	0x11, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x12, 0x3f, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x45, 0x6e, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x65, 0x6e, 0x63, 0x68, 0x61, 0x6e, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x73, 0x22, 0x56, 0x0a, 0x13, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x74, 0x74, 0x65, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x3f, 0x0a, 0x0d, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49,
	0x74, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x52, 0x0d, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0e, 0x53,
	0x49, 0x74, 0x65, 0x6d, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x2e, 0x0a, 0x06, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x35, 0x0a, 0x05, 0x53, 0x50, 0x65, 0x72, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x72, 0x6b, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x06, 0x53, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6c,
	0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x49, 0x64, 0x22, 0x66, 0x0a, 0x06, 0x53, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x09, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0d, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x70, 0x65, 0x6c, 0x6c, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x06, 0x53, 0x4d,
	0x75, 0x73, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x22, 0x75, 0x0a, 0x0b, 0x53, 0x53, 0x68, 0x61, 0x70, 0x65, 0x53, 0x68, 0x69, 0x66,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x68, 0x61, 0x70, 0x65, 0x53, 0x68, 0x69, 0x66, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x68, 0x61, 0x70, 0x65, 0x53, 0x68,
	0x69, 0x66, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x6e,
	0x64, 0x65, 0x78, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x73, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x7a, 0x0a, 0x14, 0x53, 0x43, 0x55,
	0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45, 0x5f, 0x43, 0x48, 0x41, 0x52, 0x41, 0x43, 0x54, 0x45,
	0x52, 0x12, 0x32, 0x0a, 0x14, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x14, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63,
	0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x69, 0x73, 0x4e, 0x65, 0x77, 0x22, 0x6b, 0x0a, 0x0f, 0x53, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d,
	0x49, 0x5a, 0x45, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x4e,
	0x65, 0x77, 0x22, 0x7b, 0x0a, 0x15, 0x53, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45,
	0x5f, 0x41, 0x52, 0x4d, 0x4f, 0x52, 0x5f, 0x53, 0x4b, 0x49, 0x4e, 0x12, 0x32, 0x0a, 0x14, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x53, 0x6b, 0x69,
	0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x63, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x69, 0x7a, 0x65, 0x41, 0x72, 0x6d, 0x6f, 0x72, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x4e,
	0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x22,
	0x60, 0x0a, 0x06, 0x53, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6d, 0x6f,
	0x74, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6d, 0x6f, 0x74,
	0x65, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6c, 0x6f, 0x74,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x73, 0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65,
	0x77, 0x22, 0x71, 0x0a, 0x11, 0x53, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x69, 0x7a, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x69, 0x7a, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x73, 0x4e, 0x65, 0x77, 0x22, 0x7a, 0x0a, 0x16, 0x53, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49,
	0x5a, 0x45, 0x5f, 0x4c, 0x4f, 0x42, 0x42, 0x59, 0x5f, 0x45, 0x4d, 0x4f, 0x54, 0x45, 0x12, 0x22,
	0x0a, 0x0c, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x45, 0x6d, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x6f, 0x62, 0x62, 0x79, 0x45, 0x6d, 0x6f, 0x74, 0x65,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73,
	0x4e, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77,
	0x22, 0x69, 0x0a, 0x15, 0x53, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45, 0x5f, 0x4c,
	0x4f, 0x42, 0x42, 0x59, 0x5f, 0x53, 0x4b, 0x49, 0x4e, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x6f, 0x62,
	0x62, 0x79, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6c, 0x6f, 0x62, 0x62, 0x79, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x69,
	0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x73,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x22, 0x70, 0x0a, 0x14, 0x53,
	0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d, 0x49, 0x5a, 0x45, 0x5f, 0x4e, 0x41, 0x4d, 0x45, 0x50, 0x4c,
	0x41, 0x54, 0x45, 0x12, 0x28, 0x0a, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6e, 0x61,
	0x6d, 0x65, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x69, 0x73, 0x45, 0x71, 0x75, 0x69, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x73, 0x4e, 0x65, 0x77, 0x22, 0xaf, 0x01,
	0x0a, 0x17, 0x53, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x11, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x3c, 0x0a, 0x10, 0x72, 0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x49, 0x74, 0x65,
	0x6d, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43,
	0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x10, 0x72,
	0x65, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x49, 0x74, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22,
	0xe8, 0x01, 0x0a, 0x12, 0x53, 0x47, 0x61, 0x74, 0x68, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x48, 0x61,
	0x6c, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x28, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x44, 0x43, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x2e, 0x53, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x58, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x70, 0x6f, 0x73, 0x58, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x59, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x73, 0x5a,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x70, 0x6f, 0x73, 0x5a, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x6f, 0x74, 0x50, 0x69, 0x74, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08,
	0x72, 0x6f, 0x74, 0x50, 0x69, 0x74, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x74, 0x59,
	0x61, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x72, 0x6f, 0x74, 0x59, 0x61, 0x77,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x6f, 0x74, 0x52, 0x6f, 0x6c, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x72, 0x6f, 0x74, 0x52, 0x6f, 0x6c, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x68, 0x61,
	0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x68, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x31, 0x0a, 0x10, 0x63, 0x6f,
	0x6d, 0x2e, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x42, 0x04,
	0x69, 0x74, 0x65, 0x6d, 0x50, 0x00, 0x5a, 0x15, 0x64, 0x61, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file___Item_proto_rawDescOnce sync.Once
	file___Item_proto_rawDescData = file___Item_proto_rawDesc
)

func file___Item_proto_rawDescGZIP() []byte {
	file___Item_proto_rawDescOnce.Do(func() {
		file___Item_proto_rawDescData = protoimpl.X.CompressGZIP(file___Item_proto_rawDescData)
	})
	return file___Item_proto_rawDescData
}

var file___Item_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file___Item_proto_goTypes = []interface{}{
	(*SItemMeta)(nil),               // 0: DC.Packet.SItemMeta
	(*SItem)(nil),                   // 1: DC.Packet.SItem
	(*SItemProperties)(nil),         // 2: DC.Packet.SItemProperties
	(*SItemProperty)(nil),           // 3: DC.Packet.SItemProperty
	(*SItemEnchantInfo)(nil),        // 4: DC.Packet.SItemEnchantInfo
	(*SItemEnchantInfos)(nil),       // 5: DC.Packet.SItemEnchantInfos
	(*SItemPermittedInfos)(nil),     // 6: DC.Packet.SItemPermittedInfos
	(*SItemPermitted)(nil),          // 7: DC.Packet.SItemPermitted
	(*SItems)(nil),                  // 8: DC.Packet.SItems
	(*SPerk)(nil),                   // 9: DC.Packet.SPerk
	(*SSkill)(nil),                  // 10: DC.Packet.SSkill
	(*SSpell)(nil),                  // 11: DC.Packet.SSpell
	(*SMusic)(nil),                  // 12: DC.Packet.SMusic
	(*SShapeShift)(nil),             // 13: DC.Packet.SShapeShift
	(*SCUSTOMIZE_CHARACTER)(nil),    // 14: DC.Packet.SCUSTOMIZE_CHARACTER
	(*SCUSTOMIZE_ITEM)(nil),         // 15: DC.Packet.SCUSTOMIZE_ITEM
	(*SCUSTOMIZE_ARMOR_SKIN)(nil),   // 16: DC.Packet.SCUSTOMIZE_ARMOR_SKIN
	(*SEMOTE)(nil),                  // 17: DC.Packet.SEMOTE
	(*SCUSTOMIZE_ACTION)(nil),       // 18: DC.Packet.SCUSTOMIZE_ACTION
	(*SCUSTOMIZE_LOBBY_EMOTE)(nil),  // 19: DC.Packet.SCUSTOMIZE_LOBBY_EMOTE
	(*SCUSTOMIZE_LOBBY_SKIN)(nil),   // 20: DC.Packet.SCUSTOMIZE_LOBBY_SKIN
	(*SCUSTOMIZE_NAMEPLATE)(nil),    // 21: DC.Packet.SCUSTOMIZE_NAMEPLATE
	(*SFriendItemRecoveryInfo)(nil), // 22: DC.Packet.SFriendItemRecoveryInfo
	(*SGatheringHallItem)(nil),      // 23: DC.Packet.SGatheringHallItem
}
var file___Item_proto_depIdxs = []int32{
	3,  // 0: DC.Packet.SItem.primaryPropertyArray:type_name -> DC.Packet.SItemProperty
	3,  // 1: DC.Packet.SItem.secondaryPropertyArray:type_name -> DC.Packet.SItemProperty
	4,  // 2: DC.Packet.SItem.secondaryEnchantArray:type_name -> DC.Packet.SItemEnchantInfo
	7,  // 3: DC.Packet.SItem.permittedAreaArray:type_name -> DC.Packet.SItemPermitted
	3,  // 4: DC.Packet.SItemProperties.properties:type_name -> DC.Packet.SItemProperty
	4,  // 5: DC.Packet.SItemEnchantInfos.enchantInfos:type_name -> DC.Packet.SItemEnchantInfo
	7,  // 6: DC.Packet.SItemPermittedInfos.permittedList:type_name -> DC.Packet.SItemPermitted
	1,  // 7: DC.Packet.SItems.item:type_name -> DC.Packet.SItem
	1,  // 8: DC.Packet.SFriendItemRecoveryInfo.recoveryItemList:type_name -> DC.Packet.SItem
	1,  // 9: DC.Packet.SGatheringHallItem.origin:type_name -> DC.Packet.SItem
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file___Item_proto_init() }
func file___Item_proto_init() {
	if File___Item_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file___Item_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemProperties); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemProperty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemEnchantInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemEnchantInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemPermittedInfos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItemPermitted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPerk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSkill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SSpell); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SMusic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SShapeShift); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_CHARACTER); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_ITEM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_ARMOR_SKIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SEMOTE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_ACTION); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_LOBBY_EMOTE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_LOBBY_SKIN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SCUSTOMIZE_NAMEPLATE); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SFriendItemRecoveryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___Item_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SGatheringHallItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file___Item_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___Item_proto_goTypes,
		DependencyIndexes: file___Item_proto_depIdxs,
		MessageInfos:      file___Item_proto_msgTypes,
	}.Build()
	File___Item_proto = out.File
	file___Item_proto_rawDesc = nil
	file___Item_proto_goTypes = nil
	file___Item_proto_depIdxs = nil
}
