name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and publish
        uses: wangyoucao577/go-release-action@v1
        env:
          CGO_ENABLED: 0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.22"
          project_path: "./cmd/dad_proxy"
          binary_name: "dad_proxy"
          pre_command: export CGO_ENABLED=0
          ldflags: "-s -w"
          extra_files: README.md
